### PR TITLE
Book Methods

### PR DESCRIPTION
**Pull request by carlylechia**
To complete this milestone, I worked on the following issues:

- [Created a book class](https://github.com/carlylechia/CATALOGUE/projects/1#card-84669518)
- [Created a label class](https://github.com/carlylechia/CATALOGUE/projects/1#card-84669551)
- [Defined all properties as on the diagram](https://github.com/carlylechia/CATALOGUE/projects/1#card-84669741)
- [Made available options to add books, list all books, list all labels](https://github.com/carlylechia/CATALOGUE/projects/1#card-84670991)
- [Implemented required methods](https://github.com/carlylechia/CATALOGUE/projects/1#card-84670347)
- [Preserved data on files](https://github.com/carlylechia/CATALOGUE/projects/1#card-84671034)

Thank you for reviewing this branch.

### CODE REVIEW

**Review by nottherealalanturing — APPROVED** [review]
Excellent job.  
- [x] Implement project requirements
- [ ] Professional commit messages.
- [x] Clean code base 
- [x] no linter errors. 
Nothing else to add, go ahead and merge.

**Review by Ogaga01 — CHANGES_REQUESTED** [review]
## Invalid Request
Hello @carlylechia 
This pull request has linters errors and is hereby invalid. Please fix these errors and submit resubmit the pull request.

**Review by Ogaga01 — APPROVED** [review]
## Hi @carlylechia 
Great job implementing the changes required.
There's nothing more to say than it's time to merge

**Comment by carlylechia** [comment]
Thanks guys @nottherealalanturing @Ogaga01

**Pull request merged**
